var c = {
    host: "https://app.kkid.vip/kshop-appc/kscrest.htm",
    kscSpShopIndex: "ksc.sp.shop.index",
    kscSpShopIndexItem2: "ksc.sp.shop.index.item2",
    kscPdCategoryShoptree: "ksc.pd.category.shoptree",
    kscPdItemQuery: "ksc.pd.item.query",
    kscPdItemInfo: "ksc.pd.item.info",
    kscPdItemForhwq: "ksc.pd.item.forhwq",
    kscUcSubscribeSaleSave: "ksc.uc.subscribe.sale.save",
    kscUcSubscribeSaleDelete: "ksc.uc.subscribe.sale.delete",
    kscUcSubscribeStockSave: "ksc.uc.subscribe.stock.save",
    kscUcSubscribeStockDelete: "ksc.uc.subscribe.stock.delete",
    kscMkDiscountInfo: "ksc.mk.discount.info",
    kscMkDiscountItemQuery: "ksc.mk.discount.item.query",
    kscOcCartChange: "ksc.oc.cart.change",
    kscOcCartSave: "ksc.oc.cart.save",
    kscOcCartList: "ksc.oc.cart.list",
    kscOcCartDelete: "ksc.oc.cart.delete",
    kscOcCartCount: "ksc.oc.cart.count",
    kscOcOrderPresave2: "ksc.oc.order.presave2",
    kscUcAddressDefaultSave: "ksc.uc.address.default.save",
    kscUcRealDefaultInfo: "ksc.uc.real.default.info",
    kscUcRealDefaultSave: "ksc.uc.real.default.save",
    kscBsOssUpload: "ksc.bs.oss.upload",
    kscOcOrderSave: "ksc.oc.order.save",
    kscOcOrderRepay: "ksc.oc.order.repay",
    kscOcOrderCancel: "ksc.oc.order.cancel",
    kscOcOrderQuery: "ksc.oc.order.query",
    kscOcOrderInfo: "ksc.oc.order.info",
    kscPdSpuCommentQuery: "ksc.pd.spu.comment.query",
    kscOcOrderReceive: "ksc.oc.order.receive",
    kscOcOrderExpressTrace: "ksc.oc.order.express.trace",
    kscOcOrderforcommentList: "ksc.oc.orderforcomment.list",
    kscOcCommentSave: "ksc.oc.comment.save",
    kscUcUserWxLogin: "ksc.uc.user.wx.login",
    kscUcUserWxBindmobile: "ksc.uc.user.wx.bindmobile",
    kscUcUserInfo: "ksc.uc.user.info",
    kscOcOrderCount: "ksc.oc.order.count",
    kscUcUserIndex: "ksc.uc.user.index",
    kscSpShopInfo: "ksc.sp.shop.info",
    kscSpShopCustomerList: "ksc.sp.shop.customer.list",
    kscSpShopCustomerSave: "ksc.sp.shop.customer.save",
    kscUcsSubscribeFavoriteQuery: "ksc.uc.subscribe.favorite.query",
    kscUcSubscribeFavoriteSave: "ksc.uc.subscribe.favorite.save",
    kscUcSubscribeFavoriteDelete: "ksc.uc.subscribe.favorite.delete"
};

module.exports = c;